name: sam2_env
channels:
  - conda-forge
dependencies:
  - _libavif_api=1.3.0
  - aom=3.9.1
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - dav1d=1.2.1
  - double-conversion=3.3.1
  - ffmpeg=8.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.2.2
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.44.4
  - glslang=16.0.0
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - imath=3.2.2
  - jasper=4.2.8
  - khronos-opencl-icd-loader=2024.10.24
  - krb5=1.21.3
  - lame=3.100
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libasprintf=0.22.5
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libclang13=21.1.5
  - libcurl=8.17.0
  - libdeflate=1.25
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgettextpo=0.22.5
  - libglib=2.86.1
  - libhwloc=2.12.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libogg=1.3.5
  - libopencv=4.12.0
  - libopenvino=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-intel-cpu-plugin=2025.2.0
  - libopenvino-intel-gpu-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.5.2
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - librsvg=2.60.0
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libusb=1.0.29
  - libvorbis=1.3.7
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.5
  - mkl=2025.3.0
  - numpy=2.3.4
  - opencl-headers=2025.06.13
  - opencv=4.12.0
  - openexr=3.4.3
  - openh264=2.6.0
  - openjph=0.25.0
  - openssl=3.5.4
  - pango=1.56.4
  - pcre2=10.46
  - pip=25.2
  - pixman=0.46.4
  - pugixml=1.15
  - py-opencv=4.12.0
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.11.14
  - python_abi=3.11
  - qt6-main=6.9.3
  - rav1e=0.7.1
  - requests=2.32.5
  - sdl2=2.32.56
  - sdl3=3.2.26
  - setuptools=80.9.0
  - shaderc=2025.4
  - snappy=1.2.2
  - spirv-tools=2025.4
  - svt-av1=3.1.2
  - tbb=2022.3.0
  - tk=8.6.13
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - x264=1!164.3095
  - x265=3.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - antlr4-python3-runtime==4.9.3
      - colorama==0.4.6
      - filelock==3.20.0
      - fsspec==2025.10.0
      - hydra-core==1.3.2
      - iopath==0.1.10
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.5
      - omegaconf==2.3.0
      - packaging==25.0
      - pillow==12.0.0
      - portalocker==3.2.0
      - pywin32==311
      - pyyaml==6.0.3
      - sam-2==1.0
      - sympy==1.14.0
      - torch==2.9.0
      - torchvision==0.24.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
